### ISSUE TITLE
Créer la BDD SQLite

### ISSUE THREAD

**Issue by cclaim** [hugohil/EMM-projet2#10]

**Comment by cclaim** [comment]
#8 related.

-> Ajouter les annotations sur les champs des classes pour Jackson (le nom des champs dans le JSON et dans le modèle java diffère parfois)

http://hmkcode.com/android-simple-sqlite-database-tutorial/

**Comment by hugohil** [comment]
Créer une base référençant les categories et sous-catégories présents pour vérifier rapidement leur présence ou non et faire la requete serveur ou SQLite
